GET http://localhost:3000/bidder

###

POST http://localhost:3000/register/
Content-Type: application/json

{
    "cname":"great componey",
    "lnumber":12,
    "email":"a@a.com",
    "location":"Eritrea",
    "uname":"abc",
    "pwd":"abc"
}

###
POST http://localhost:3000/profile/
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="5f.jpg"
Content-Type: image/jpeg

< ./5f.jpg

--MyBoundary--
###
DELETE http://localhost:3000/students/2

